version: "3"
services:
  database:
    image: postgis/postgis:15-3.3-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      - POSTGRES_DB=directus
      - POSTGRES_USER=directus
      - POSTGRES_PASSWORD=directus
    ports:
      - 5432:5432
    networks:
      - directus-network

  pgadmin:
    image: dpage/pgadmin4:latest
    volumes:
      - pgadmin4_data:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=dev@devix.co
      - PGADMIN_DEFAULT_PASSWORD=directus
    restart: unless-stopped
    depends_on:
      - database
    ports:
      - 16543:80
    networks:
      - directus-network

  directus:
    image: directus/directus:11.3.5
    env_file: .env # Carrega as variáveis do arquivo .env
    ports:
      - 8055:8055
    volumes:
      - .:/directus/extensions/directus-extension-here
    depends_on:
      - database
    networks:
      - directus-network
    restart: unless-stopped

volumes:
  db_data:
  pgadmin4_data:

networks:
  directus-network:
    driver: bridge
